"""initial_schema_neon_postgresql

Revision ID: 91fa6d11284b
Revises: 
Create Date: 2026-09-09 10:12:00.880482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fa6d11284b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_title', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('baseline_placement_rate', sa.Float(), nullable=True),
    sa.Column('post_placement_rate', sa.Float(), nullable=True),
    sa.Column('baseline_retention_rate', sa.Float(), nullable=True),
    sa.Column('post_retention_rate', sa.Float(), nullable=True),
    sa.Column('baseline_avg_wage', sa.Float(), nullable=True),
    sa.Column('post_avg_wage', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('evaluation_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_measurements', schema=None) as batch_op:
        batch_op.create_index('ix_impact_entity_period', ['entity_type', 'period'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('experience_months', sa.Integer(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_district', ['district'], unique=False)
        batch_op.create_index('ix_jobs_sector_state', ['sector', 'state'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('demand_weight', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('ix_skills_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)
        batch_op.create_index('ix_skills_sector', ['sector'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    op.create_table('training_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('accreditation_tier', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('active_learners_count', sa.Integer(), nullable=True),
    sa.Column('overall_placement_rate', sa.Float(), nullable=True),
    sa.Column('overall_retention_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_providers', schema=None) as batch_op:
        batch_op.create_index('ix_tp_state_district', ['state', 'district'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_providers_code'), ['code'], unique=True)

    op.create_table('programmes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('scheme_name', sa.String(length=150), nullable=False),
    sa.Column('nsqf_level', sa.Integer(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('total_enrolled', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('certified_count', sa.Integer(), nullable=True),
    sa.Column('placed_count', sa.Integer(), nullable=True),
    sa.Column('avg_starting_wage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programmes_code'), ['code'], unique=True)
        batch_op.create_index('ix_programmes_provider', ['provider_id'], unique=False)
        batch_op.create_index('ix_programmes_scheme', ['scheme_name'], unique=False)
        batch_op.create_index('ix_programmes_sector', ['sector'], unique=False)

    op.create_table('learners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('current_programme_id', sa.String(length=36), nullable=True),
    sa.Column('learner_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=False),
    sa.Column('socio_economic_category', sa.String(length=50), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('profile_completion_pct', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('current_salary', sa.Float(), nullable=True),
    sa.Column('retention_milestone_reached', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('skill_match_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("risk_level IN ('Low', 'Medium', 'High')", name='chk_learner_risk_level'),
    sa.CheckConstraint('age >= 14', name='chk_learner_age'),
    sa.ForeignKeyConstraint(['current_programme_id'], ['programmes.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learners_learner_code'), ['learner_code'], unique=True)
        batch_op.create_index('ix_learners_programme', ['current_programme_id'], unique=False)
        batch_op.create_index('ix_learners_provider', ['provider_id'], unique=False)
        batch_op.create_index('ix_learners_state_district', ['state', 'district'], unique=False)
        batch_op.create_index('ix_learners_status_risk', ['current_status', 'risk_level'], unique=False)

    op.create_table('apprenticeship_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('establishment_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('stipend_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stipend_amount >= 0', name='chk_app_stipend'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apprenticeship_outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_app_learner', ['learner_id'], unique=False)
        batch_op.create_index('ix_app_sector', ['sector'], unique=False)

    op.create_table('employment_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('monthly_salary >= 0', name='chk_emp_salary'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_emp_learner_status', ['learner_id', 'status'], unique=False)
        batch_op.create_index('ix_emp_sector', ['sector'], unique=False)
        batch_op.create_index('ix_emp_verified', ['verified'], unique=False)

    op.create_table('followups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('milestone', sa.String(length=50), nullable=False),
    sa.Column('followup_date', sa.String(length=50), nullable=False),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('current_salary', sa.Float(), nullable=True),
    sa.Column('retention_status', sa.String(length=50), nullable=True),
    sa.Column('job_satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('skill_relevance_score', sa.Integer(), nullable=True),
    sa.Column('attrition_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('surveyor_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('job_satisfaction_score BETWEEN 1 AND 5', name='chk_followup_job_sat'),
    sa.CheckConstraint('skill_relevance_score BETWEEN 1 AND 5', name='chk_followup_skill_rel'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'milestone', name='uq_learner_milestone')
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index('ix_followup_learner_milestone', ['learner_id', 'milestone'], unique=False)
        batch_op.create_index('ix_followup_retention', ['retention_status'], unique=False)

    op.create_table('interventions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_by', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_completion_date', sa.String(length=50), nullable=False),
    sa.Column('completed_date', sa.String(length=50), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index('ix_int_category', ['category'], unique=False)
        batch_op.create_index('ix_int_learner_status', ['learner_id', 'status'], unique=False)

    op.create_table('learner_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('assessed_score', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('acquired_from', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'skill_id', name='uq_learner_skill')
    )
    with op.batch_alter_table('learner_skills', schema=None) as batch_op:
        batch_op.create_index('ix_ls_learner_skill', ['learner_id', 'skill_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('positive_factors', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('recommended_interventions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('probability BETWEEN 0.0 AND 1.0', name='chk_pred_probability'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_pred_learner_type', ['learner_id', 'prediction_type'], unique=False)
        batch_op.create_index('ix_pred_risk_level', ['risk_level'], unique=False)

    op.create_table('self_employment_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('monthly_revenue', sa.Float(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('microfinance_support', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('monthly_revenue >= 0', name='chk_self_revenue'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('self_employment_outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_self_emp_learner', ['learner_id'], unique=False)
        batch_op.create_index('ix_self_emp_sector', ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_employment_outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_self_emp_sector')
        batch_op.drop_index('ix_self_emp_learner')

    op.drop_table('self_employment_outcomes')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_pred_risk_level')
        batch_op.drop_index('ix_pred_learner_type')

    op.drop_table('predictions')
    with op.batch_alter_table('learner_skills', schema=None) as batch_op:
        batch_op.drop_index('ix_ls_learner_skill')

    op.drop_table('learner_skills')
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_index('ix_int_learner_status')
        batch_op.drop_index('ix_int_category')

    op.drop_table('interventions')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index('ix_followup_retention')
        batch_op.drop_index('ix_followup_learner_milestone')

    op.drop_table('followups')
    with op.batch_alter_table('employment_outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_emp_verified')
        batch_op.drop_index('ix_emp_sector')
        batch_op.drop_index('ix_emp_learner_status')

    op.drop_table('employment_outcomes')
    with op.batch_alter_table('apprenticeship_outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_app_sector')
        batch_op.drop_index('ix_app_learner')

    op.drop_table('apprenticeship_outcomes')
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_index('ix_learners_status_risk')
        batch_op.drop_index('ix_learners_state_district')
        batch_op.drop_index('ix_learners_provider')
        batch_op.drop_index('ix_learners_programme')
        batch_op.drop_index(batch_op.f('ix_learners_learner_code'))

    op.drop_table('learners')
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.drop_index('ix_programmes_sector')
        batch_op.drop_index('ix_programmes_scheme')
        batch_op.drop_index('ix_programmes_provider')
        batch_op.drop_index(batch_op.f('ix_programmes_code'))

    op.drop_table('programmes')
    with op.batch_alter_table('training_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_providers_code'))
        batch_op.drop_index('ix_tp_state_district')

    op.drop_table('training_providers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('ix_skills_sector')
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index('ix_skills_category')

    op.drop_table('skills')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_sector_state')
        batch_op.drop_index('ix_jobs_district')

    op.drop_table('jobs')
    with op.batch_alter_table('impact_measurements', schema=None) as batch_op:
        batch_op.drop_index('ix_impact_entity_period')

    op.drop_table('impact_measurements')
    # ### end Alembic commands ###
